### PR TITLE
Match customer_create method to underlying API

### PR DESCRIPTION
**Pull request by mattty**
Adds support for `locale` and `groups` options to customer_create API method.

Not sure if this is on your roadmap, but this would be a useful addition. 

Note this may be a breaking change for folks passing in a data hash without curly braces.

### CODE REVIEW

**Comment by joram** [comment]
Hey @matty, thanks for the p.r. I'm just starting to read over your proposed changes now.

**Comment by joram** [comment]
Hey @mattty, reading over this p.r. it seems like it adds functionality. My concern is your comment regarding passing a data hash. I'm not sure what you mean by this, could you give me an example?

**Comment by mattty** [comment]
Hi @joram! 

My comment was that folks passing calling `customer_create` like this:
`customer_create 'email@domain.com', key1: 'val1', key2: 'val2'`
would have their implementation broken by the change to the method signature. But I was mistaken -- calling the new method in this manner still works.

**Comment by joram** [comment]
@matty, thanks, I will locally check that shortly.

**Pull request merged**
